"use client";
import { useEffect, useState } from "react";
import { ProductEditor, type EditableProduct } from "./ProductEditor";
type Row = EditableProduct & { id: string; name: string; price: string; currency: string; availability: string; isVisible: boolean; isFeatured: boolean; displayOrder: number; sourceVisible: boolean; sourceConnectionId: string | null; sourceConnection: { provider: string } | null };
export function ProductManager() {
  const [rows, setRows] = useState<Row[]>([]), [query, setQuery] = useState(""), [page, setPage] = useState(1), [pages, setPages] = useState(0), [revision, setRevision] = useState(0), [status, setStatus] = useState(""), [busy, setBusy] = useState(false), [editing, setEditing] = useState<Row | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/admin/products?q=${encodeURIComponent(query)}&page=${page}&limit=12`, { signal: controller.signal, cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("Could not load products."); return response.json(); }).then((result) => { setRows(result.data); setPages(result.pagination.totalPages); }).catch(() => { if (!controller.signal.aborted) setStatus("Could not load products. Check your session."); }); return () => controller.abort(); }, [query, page, revision]);
  async function mutate(path: string, method: string, body?: unknown) { setBusy(true); setStatus(""); try { const response = await fetch(path, { method, headers: { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Save failed."); setStatus("Product saved."); setRevision((v) => v + 1); setEditing(null); } catch (error) { setStatus(error instanceof Error ? error.message : "Save failed."); } finally { setBusy(false); } }
  return <section className="mt-10 grid gap-4"><h2 className="text-xl font-semibold">Product management</h2><p>Imported names and prices follow their store. Visibility, featured status and order stay local.</p>
    <form onSubmit={(event) => { event.preventDefault(); setQuery(String(new FormData(event.currentTarget).get("q") ?? "")); setPage(1); }} className="flex flex-wrap gap-3"><label>Search all sources<input className="ml-2 rounded border bg-white p-3" name="q" maxLength={100} /></label><button className="button">Search products</button></form>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Product / source</th><th className="p-2">Price</th><th className="p-2">Local controls</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="p-2">{row.name}<br /><span className="text-slate-600">{row.sourceConnection?.provider ?? "LOCAL"}{!row.sourceVisible ? " · hidden by source" : ""}</span></td><td className="p-2">{row.currency} {row.price}</td><td className="flex flex-wrap gap-2 p-2"><button disabled={busy} className="button button-secondary" onClick={() => void mutate(`/api/admin/products/${row.id}`, "PATCH", { isVisible: !row.isVisible })}>{row.isVisible ? "Hide" : "Show"}</button><button disabled={busy} className="button button-secondary" onClick={() => void mutate(`/api/admin/products/${row.id}`, "PATCH", { isFeatured: !row.isFeatured })}>{row.isFeatured ? "Unfeature" : "Feature"}</button><label>Order<input className="w-20 rounded border bg-white p-2" aria-label={`Display order for ${row.name}`} type="number" min={0} max={100000} defaultValue={row.displayOrder} key={`${row.id}-${row.displayOrder}`} onBlur={(event) => { const value = Number(event.target.value); if (Number.isInteger(value) && value >= 0 && value <= 100000 && value !== row.displayOrder) void mutate(`/api/admin/products/${row.id}`, "PATCH", { displayOrder: value }); }} /></label>{!row.sourceConnectionId && <button className="button button-secondary" disabled={busy} onClick={() => setEditing(row)}>Edit</button>}</td></tr>)}</tbody></table></div>
    {!rows.length && <p>No matching products.</p>}<div className="flex items-center gap-3"><button className="button button-secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous products</button><span>Page {page} of {Math.max(1, pages)}</span><button className="button button-secondary" disabled={page >= pages} onClick={() => setPage(page + 1)}>Next products</button></div>
    <ProductEditor key={`${editing?.id ?? "new"}-${revision}`} product={editing} busy={busy} cancel={() => setEditing(null)} save={(data) => mutate(`/api/admin/products${editing ? `/${editing.id}` : ""}`, editing ? "PATCH" : "POST", data)} /><p role="status">{status}</p>
  </section>;
}
